// constants/glossary.ts
export const GLOSSARY_PORTS: Record<string, { port: string; definition: string }[]> = {
    'CompTIA Network+': [
        { port: '80', definition: 'HTTP – Hypertext Transfer Protocol' },
        { port: '443', definition: 'HTTPS – Hypertext Transfer Protocol Secure' },
        { port: '20/21', definition: 'FTP – File Transfer Protocol' },
        { port: '22', definition: 'SSH – Secure Shell' },
        { port: '25', definition: 'SMTP – Simple Mail Transfer Protocol' },
        { port: '53', definition: 'DNS – Domain Name System' },
        { port: '67/68', definition: 'DHCP – ' },
        { port: '69', definition: 'HTTPS – Hypertext Transfer Protocol Secure' },
        { port: '123', definition: 'FTP – File Transfer Protocol' },
        { port: '161/162', definition: 'SSH – Secure Shell' },
        { port: '389', definition: 'SMTP – Simple Mail Transfer Protocol' },
        { port: '445', definition: 'DNS – Domain Name System' },
        { port: '514', definition: 'HTTP – Hypertext Transfer Protocol' },
        { port: '587', definition: 'HTTPS – Hypertext Transfer Protocol Secure' },
        { port: '636', definition: 'FTP – File Transfer Protocol' },
        { port: '1433', definition: 'SSH – Secure Shell' },
        { port: '3389', definition: 'SMTP – Simple Mail Transfer Protocol' },
        { port: '5060.5061', definition: 'DNS – Domain Name System' },
        { port: '22', definition: 'SMTP – Simple Mail Transfer Protocol' },
        { port: '23', definition: 'DNS – Domain Name System' }    ],
};
export const GLOSSARY_TERMS: Record<string, { term: string; definition: string }[]> = {
    'CompTIA A+ Core 1': [
        { term: 'BIOS', definition: 'Basic Input/Output System; initializes hardware at startup.' },
        { term: 'IP Address', definition: 'A unique identifier for devices on a network.' },
        { term: 'Virtualization', definition: 'Running multiple OS environments on one physical machine.' },
    ],
    'CompTIA A+ Core 2': [
        { term: 'Registry', definition: 'Windows database storing OS and application settings.' },
        { term: 'Malware', definition: 'Software designed to harm, exploit, or disable computers.' },
    ],
    'CompTIA Network+': {
        '1.0 Networking Concepts': [
            { term: 'OSI Model', definition: 'Conceptual model with 7 layers for network communication.' },
            { term: 'TCP/IP', definition: 'Protocol suite for internet and network communication.' },
    ],}
};

export const GLOSSARY_ACRONYMS: Record<string, { acronym: string; definition: string }[]> = {
    'CompTIA Network+': [
        { acronym: 'IPAM', definition: 'IP Address Management' },
        { acronym: 'DHCP', definition: 'Dynamic Host Configuration Protocol' },
        { acronym: 'DNS', definition: 'Domain Name System' },
        { acronym: 'VPN', definition: 'Virtual Private Network' },
    ],
    'CompTIA Security+': [
        { acronym: 'ACL', definition: 'Access Control List' },
        { acronym: 'MFA', definition: 'Multi-Factor Authentication' },
    ],
};
export const GLOSSARY_ACRONYMS_BY_OBJECTIVE: Record<
    string,
    {
        [objective: string]: { acronym: string; definition: string }[];
    }
> = {
    'CompTIA Network+': {
        '1.0 Networking Concepts': [
            { acronym: 'IP', definition: 'Internet Protocol' },
            { acronym: 'IPAM', definition: 'IP Address Management' },
            { acronym: 'ARP', definition: 'Address Resolution Protocol' },
            { acronym: 'DNS', definition: 'Domain Name System' },
            { acronym: 'DNSSEC', definition: 'Domain Name System Security Extensions' },
            { acronym: 'DoH', definition: 'DNS over Hypertext Transfer Protocol Secure' },
            { acronym: 'DoT', definition: 'DNS over Transport Layer Security' },
            { acronym: 'DHCP', definition: 'Dynamic Host Configuration Protocol' },
            { acronym: 'ICMP', definition: 'Internet Control Message Protocol' },
            { acronym: 'IPSec', definition: 'Internet Protocol Security' },
            { acronym: 'OSI', definition: 'Open Systems Interconnection' },
            { acronym: 'TCP', definition: 'Transmission Control Protocol' },
            { acronym: 'UDP', definition: 'User Datagram Protocol' },
            { acronym: 'HTTP', definition: 'Hypertext Transfer Protocol' },
            { acronym: 'HTTPS', definition: 'Hypertext Transfer Protocol Secure' },
        ],
        '2.0 Network Implementation': [
            { acronym: 'LAN', definition: 'Local Area Network' },
            { acronym: 'WAN', definition: 'Wide Area Network' },
            { acronym: 'VLAN', definition: 'Virtual Local Area Network' },
            { acronym: 'SSID', definition: 'Service Set Identifier' },
            { acronym: 'BSSID', definition: 'Basic Service Set Identifier' },
            { acronym: 'AP', definition: 'Access Point' },
            { acronym: 'MX', definition: 'Mail Exchange' },
            { acronym: 'PoE', definition: 'Power over Ethernet' },
            { acronym: 'PAT', definition: 'Port Address Translation' },
            { acronym: 'NAT', definition: 'Network Address Translation' },
            { acronym: 'NIC', definition: 'Network Interface Cards' },
            { acronym: 'IDF', definition: 'Intermediate Distribution Frame' },
            { acronym: 'MDF', definition: 'Main Distribution Frame' },
            { acronym: 'DSL', definition: 'Digital Subscriber Line' },
            { acronym: 'WAN', definition: 'Wide Area Network' },
            { acronym: 'LAN', definition: 'Local Area Network' },
            { acronym: 'UTP', definition: 'Unshielded Twisted Pair' },
            { acronym: 'STP', definition: 'Shielded Twisted Pair' },
            { acronym: 'LC', definition: 'Local Connector' },
            { acronym: 'SC', definition: 'Subscriber Connector' },
            { acronym: 'BNC', definition: 'Bayonet Neill–Concelman' },
            { acronym: 'RJ', definition: 'Registered Jack' },
            { acronym: 'SFP', definition: 'Small Form-factor Pluggable' },
            { acronym: 'QSFP', definition: 'Quad Small Form-factor Pluggable' },
            { acronym: 'VLSM', definition: 'Variable Length Subnet Mask' },
            { acronym: 'CIDR', definition: 'Classless Inter-domain Routing' },
        ],
        '3.0 Network Operations': [
            { acronym: 'QoS', definition: 'Quality of Service' },
            { acronym: 'MTBF', definition: 'Mean Time Between Failure' },
            { acronym: 'MTTR', definition: 'Mean Time To Repair' },
            { acronym: 'RTO', definition: 'Recovery Time Objective' },
            { acronym: 'RPO', definition: 'Recovery Point Objective' },
            { acronym: 'SNMP', definition: 'Simple Network Management Protocol' },
            { acronym: 'NTP', definition: 'Network Time Protocol' },
            { acronym: 'NTS', definition: 'Network Time Security' },
            { acronym: 'DCI', definition: 'Data Center Interconnect' },
            { acronym: 'CAM', definition: 'Content-addressable Memory' },
            { acronym: 'CDP', definition: 'Cisco Discovery Protocol' },
        ],
        '4.0 Network Security': [
            { acronym: 'ACL', definition: 'Access Control List' },
            { acronym: 'MFA', definition: 'Multi-Factor Authentication' },
            { acronym: 'VPN', definition: 'Virtual Private Network' },
            { acronym: 'PKI', definition: 'Public Key Infrastructure' },
            { acronym: 'SSH', definition: 'Secure Shell' },
            { acronym: 'SSL', definition: 'Secure Socket Layer' },
            { acronym: 'SAML', definition: 'Security Assertion Markup Language' },
            { acronym: 'ZTA', definition: 'Zero Trust Architecture' },
            { acronym: 'DLP', definition: 'Data Loss Prevention' },
            { acronym: 'IPS', definition: 'Intrusion Prevention System' },
            { acronym: 'IDS', definition: 'Intrusion Detection System' },
            { acronym: 'EAPoL', definition: 'Extensible Authentication Protocol over LAN' },
            { acronym: 'ESP', definition: 'Encapsulating Security Payload' },
            { acronym: 'TLS', definition: 'Transport Layer Security' },
            { acronym: 'SSE', definition: 'Security Service Edge' },
            { acronym: 'SASE', definition: 'Secure Access Service Edge' },
            { acronym: 'PSK', definition: 'Pre-shared Key' },
            { acronym: 'TACAS+', definition: 'Terminal Access Controller Access Control System Plus' },
        ],
        '5.0 Network Troubleshooting': [
            { acronym: 'Ping', definition: 'Packet Internet Groper' },
            { acronym: 'Traceroute', definition: 'Trace Route Utility' },
            { acronym: 'RDP', definition: 'Remote Desktop Protocol' },
            { acronym: 'DNS', definition: 'Domain Name System' },
            { acronym: 'DHCP', definition: 'Dynamic Host Configuration Protocol' },
            { acronym: 'ARP', definition: 'Address Resolution Protocol' },
            { acronym: 'IP', definition: 'Internet Protocol' },
            { acronym: 'TTL', definition: 'Time to Live' },
            { acronym: 'PTR', definition: 'Pointer' },
            { acronym: 'VPC', definition: 'Virtual Private Cloud' },
            { acronym: 'UTM', definition: 'Unified Threat Management' },
            { acronym: 'UPS', definition: 'Uninterruptible Power Supply' },
            { acronym: 'SVI', definition: 'Switch Virtual Interface' },
            { acronym: 'NIC', definition: 'Network Interface Cards' },
        ],
    },
};
